server:
  port: 8001

spring:
  application:
    #应用名，注册进eureka的Application名称
    name: provider

#注册中心
eureka:
  instance:
    #注册进Eureka的实例Id
    instance-id: provider8001
    prefer-ip-address: true
  client:
    #设置服务注册中心的URL
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
